-- MySQL Script generated by MySQL Workbench
-- Sun Sep 10 22:41:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Persistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Persistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Persistencia` DEFAULT CHARACTER SET utf8 ;
USE `Persistencia` ;

-- -----------------------------------------------------
-- Table `Persistencia`.`Tramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`Tramite` (
  `idTramite` INT NOT NULL AUTO_INCREMENT,
  `tipoTramite` VARCHAR(45) NULL,
  `fechaTramite` DATETIME NULL,
  PRIMARY KEY (`idTramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persistencia`.`Avaluo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`Avaluo` (
  `idAvaluo` INT NOT NULL AUTO_INCREMENT,
  `lugarAvaluo` VARCHAR(100) NULL,
  `Tramite_idTramite` INT NOT NULL,
  PRIMARY KEY (`idAvaluo`),
  INDEX `fk_Avaluo_Tramite_idx` (`Tramite_idTramite` ASC),
  CONSTRAINT `fk_Avaluo_Tramite`
    FOREIGN KEY (`Tramite_idTramite`)
    REFERENCES `Persistencia`.`Tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persistencia`.`DiarioCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`DiarioCliente` (
  `idDiarioCliente` INT NOT NULL AUTO_INCREMENT,
  `entradaDiario` VARCHAR(45) NULL,
  `fechaDiario` DATETIME NULL,
  `Tramite_idTramite` INT NOT NULL,
  PRIMARY KEY (`idDiarioCliente`),
  INDEX `fk_DiarioCliente_Tramite1_idx` (`Tramite_idTramite` ASC),
  CONSTRAINT `fk_DiarioCliente_Tramite1`
    FOREIGN KEY (`Tramite_idTramite`)
    REFERENCES `Persistencia`.`Tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persistencia`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`Inmueble` (
  `idInmueble` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  PRIMARY KEY (`idInmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persistencia`.`Imgen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`Imgen` (
  `idImgen` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idImgen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persistencia`.`InmuebleImgen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persistencia`.`InmuebleImgen` (
  `idInmueble` INT NOT NULL,
  `idImgen` INT NOT NULL,
  PRIMARY KEY (`idInmueble`, `idImgen`),
  INDEX `fk_Inmueble_has_Imgen_Imgen1_idx` (`idImgen` ASC),
  INDEX `fk_Inmueble_has_Imgen_Inmueble1_idx` (`idInmueble` ASC),
  CONSTRAINT `fk_Inmueble_has_Imgen_Inmueble1`
    FOREIGN KEY (`idInmueble`)
    REFERENCES `Persistencia`.`Inmueble` (`idInmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inmueble_has_Imgen_Imgen1`
    FOREIGN KEY (`idImgen`)
    REFERENCES `Persistencia`.`Imgen` (`idImgen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
