-- MySQL Script generated by MySQL Workbench
-- Sat Sep  2 01:45:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JavaPersistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JavaPersistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JavaPersistencia` DEFAULT CHARACTER SET utf8 ;
USE `JavaPersistencia` ;

-- -----------------------------------------------------
-- Table `JavaPersistencia`.`Tramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaPersistencia`.`Tramite` (
  `idTramite` INT NOT NULL AUTO_INCREMENT,
  `tipoTramite` VARCHAR(45) NULL,
  `fechaTramite` DATETIME NULL,
  PRIMARY KEY (`idTramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaPersistencia`.`Avaluo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaPersistencia`.`Avaluo` (
  `idAvaluo` INT NOT NULL AUTO_INCREMENT,
  `lugarAvaluo` VARCHAR(100) NULL,
  `Tramite_idTramite` INT NOT NULL,
  PRIMARY KEY (`idAvaluo`),
  INDEX `fk_Avaluo_Tramite_idx` (`Tramite_idTramite` ASC),
  CONSTRAINT `fk_Avaluo_Tramite`
    FOREIGN KEY (`Tramite_idTramite`)
    REFERENCES `JavaPersistencia`.`Tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
