-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 23:58:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Practica2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Practica2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Practica2` DEFAULT CHARACTER SET utf8 ;
USE `Practica2` ;

-- -----------------------------------------------------
-- Table `Practica2`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica2`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apPaterno` VARCHAR(45) NULL,
  `apMaterno` VARCHAR(45) NULL,
  `nacimiento` DATETIME NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica2`.`Ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica2`.`Ficha` (
  `idFicha` INT NOT NULL,
  `folio` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idFicha`),
  INDEX `fk_Ficha_Persona_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Ficha_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Practica2`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
